@startuml
'https://plantuml.com/sequence-diagram

participant Sensor_Node
participant Gateway_Node
participant Topic
participant Broker
participant Server
participant Database
participant UI
actor User

title Weather Station Sequence
scale 1

Gateway_Node --> Broker : Connect <id>
Server --> Broker : Connect <id>
Gateway_Node -> Topic : Send from oldest in queue
Server -> Topic : Subscribe to /device/responses
Topic -> Server : Retrieve oldest in queue

Server -> UI : [GET] Weather_Data
Server -> Database : [UPSERT] Weather_Data

User --> UI : Update Weather Data
UI -> Server : Update Request

Server -> Topic : Publish /device/requests
Gateway_Node -> Topic : Check for requests
Gateway_Node -> Sensor_Node : Request Poll
Sensor_Node -> Gateway_Node : Weather_Data
Gateway_Node -> Topic : Publish /responses/<data>
Topic -> Server : Retrieve oldest in queue

Server -> UI : [GET] Weather_Data
Server -> Database : [UPSERT] Weather_Data
User --> UI : Request Weather Data by <date>

UI -> Server : Data Request <date>
Server -> Database : [QUERY] Weather_Data by <date>
Database -> Server : Weather_Data<date>
Server -> UI : Weather_Data<date>



@enduml